---
windows:
  hosts:
    win-test-server-1:
      ansible_host: 192.168.1.101
    win-prod-server-2:
      ansible_host: 192.168.1.102
  vars:
    ansible_user: administrator
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

linux:
  hosts:
    linux-test-server-1:
      ansible_host: 192.168.100.156
    linux-prod-server-2:
      ansible_host: 192.168.100.162
  vars:
    ansible_user: admin
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3
