---
# System updates management
- name: System Updates
  hosts: all
  tasks:
    # Windows updates
    - name: Install Windows updates
      win_updates:
        category_names: SecurityUpdates
        reboot: yes
      when: ansible_os_family == "Windows"

    # Debian/Ubuntu updates
    - name: Update apt cache and upgrade
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"

    # RHEL/CentOS updates
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"